[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Allow direct function calls from frontend on both local and production
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "POST, OPTIONS"
[dev]
  command = "vite"        # run the Vite dev server
  targetPort = 5173       # Netlify Dev will proxy to this
  framework = "#custom"
  autoLaunch = false
